language: python

python:
    - "2.7"
    - "3.5"

env:
    - TOX_ENV=py27-18
    - TOX_ENV=py27-19
    - TOX_ENV=py27-110
    - TOX_ENV=py27-111
    - TOX_ENV=py35-18
    - TOX_ENV=py35-19
    - TOX_ENV=py35-110
    - TOX_ENV=py35-111

install:
    - pip install tox

script:
    - tox -e $TOX_ENV

sudo: false